language: ruby

before-install:
- gem update --system
- gem --version
- bundle lock --add-platform ruby
- bundle lock --add-platform x86_64-linux
- npm i npm -i
- gem install bundler

after_success:
  - bundle exec codeclimate-test-reporter
  
rvm:
- 2.4.4

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec